[package]
name = "minecraft_block_finder"
version = "0.1.0"
edition = "2021"

[dependencies]
fastanvil = "0.31"
fastnbt = "2.5"
serde = { version = "1.0", features = ["derive"] }
regex = "1.11"
rayon = "1.10"
clap = { version = "4.5.21", features = ["derive"] }
toml = "0.8"